# Generated by Django 3.0.3 on 2022-12-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTb',
            fields=[
                ('id_login', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('id_loja', models.IntegerField(blank=True, null=True)),
                ('id_cargo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login_tb',
                'managed': False,
            },
        ),
    ]
