# Generated by Django 3.0.3 on 2022-12-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoTb',
            fields=[
                ('id_cargo', models.BigAutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('dt_inclusao', models.DateTimeField(blank=True, null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'cargo_tb',
                'managed': False,
            },
        ),
    ]
